# Generated by Django 5.2 on 2025-04-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundapp', '0003_admintask'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestion',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
