# Generated by Django 5.2 on 2025-04-15 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biditem',
            name='admin_notes',
        ),
        migrations.AlterField(
            model_name='biditem',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 21, 24, 46, 860506, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='biditem',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='biditem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='bidnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_bid', 'New Bid'), ('outbid', 'Outbid'), ('won', 'Won Auction'), ('ended', 'Auction Ended')], max_length=20),
        ),
    ]
