# Generated by Django 5.2 on 2025-04-17 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_alter_biditem_end_date_alter_biditem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biditem',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 8, 13, 43, 617393, tzinfo=datetime.timezone.utc)),
        ),
    ]
